[package]
name = "lemmeknow"
version = "0.2.0"
edition = "2021"
authors = ["swanandx"]
description = "Identify any mysterious text or analyze strings from a file"
readme = "README.md"
repository = "https://github.com/swanandx/lemmeknow"
homepage = "https://github.com/swanandx/lemmeknow"
license = "MIT"
keywords = ["cryptography", "cybersecurity", "regex", "forensics", "identify"]
categories = ["accessibility", "command-line-utilities", "text-processing", "parsing", "encoding"]
documentation = "https://docs.rs/lemmeknow"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
comfy-table = "5.0.1"
clap = "2.33.3"
once_cell = "1.8.0"

[profile.release]
lto = true
panic = "abort"
